export const FILTER_USERS = 'FILTER_USERS';
export const GET_SINGLE_USER = 'GET_SINGLE_USER';
export const GET_USER_REPOS = 'GET_USER_REPOS';
export const CLEAR_FILTERED_USERS = 'CLEAR_FILTERED_USERS';
export const SET_LOADING = 'SET_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
